openapi: 3.2.0
info:
  title: NeuroSan Concierge Service API
  version: 0.0.1
  description: 'The service provides system-wide information about resources available

    in current instance of neuro-san.'
tags:
- name: ConciergeService
  description: 'The service provides system-wide information about resources available

    in current instance of neuro-san.'
paths:
  /api/v1/list:
    get:
      tags:
      - ConciergeService
      summary: List
      description: Called when a client needs the information about available agents.
      operationId: ConciergeService_List
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConciergeResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    AgentInfo:
      type: object
      properties:
        agent_name:
          type: string
          description: Agent name
        description:
          type: string
          description: Outward-facing description of what the agent does.
        tags:
          type: array
          items:
            type: string
          description: Optional metadata describing where this agent falls into larger agent grouping(s).
      description: Description of an agent's function
    Status:
      type: object
      properties:
        code:
          type: integer
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
          format: int32
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/GoogleProtobufAny'
          description: A list of messages that carry the error details.  There is a common set of message types for APIs to use.
      description: 'The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).'
    GoogleProtobufAny:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the serialized message.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
    ConciergeResponse:
      type: object
      properties:
        agents:
          type: array
          items:
            $ref: '#/components/schemas/AgentInfo'
          description: List of agent descriptions
      description: Response structure for List gRPC method
